"""empty message

Revision ID: 076ec8ea032f
Revises: e4633728ab28
Create Date: 2023-02-18 11:07:47.663279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076ec8ea032f'
down_revision = 'e4633728ab28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_level', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('subject_level')

    # ### end Alembic commands ###
