"""empty message

Revision ID: 21d06ef26650
Revises: 01b6c3c5f9f7
Create Date: 2023-03-02 22:22:16.907447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d06ef26650'
down_revision = '01b6c3c5f9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=400), nullable=True),
    sa.Column('credentials', sa.String(length=400), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userTutors',
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('tutors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutors'], ['tutors.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users', 'tutors')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('userTutors')
    op.drop_table('tutors')
    # ### end Alembic commands ###
