"""empty message

Revision ID: 7c701d365db5
Revises: 58a1c8f42698
Create Date: 2023-03-30 21:52:48.535473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c701d365db5'
down_revision = '58a1c8f42698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messageHasRead', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('messageHasRead')

    # ### end Alembic commands ###
